#specify a directory to install
cask_args appdir: '/Applications'

# install cask for bigger apps
tap 'caskroom/homebrew-cask' || true



### FULL APPS

cask 'vlc'
cask 'dropbox'
cask 'firefox'
cask 'spotify'
cask 'iterm2'
cask 'transmission'
cask 'karabiner-elements'
cask 'docker'


# Fonts
# Note: may need to change font preferences in iterm2.
tap 'homebrew/cask-fonts'
cask 'font-menlo-for-powerline'
