# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/53cb9268-466a-47a9-98d4-8a8726526d3f";
      fsType = "ext4";
    };

  # Note have unused /dev/nvme0n1p6, could use for /home

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8F35-5FBC";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c17f14bb-b3f7-4c8b-856f-c274910015ee"; }   # this is /dev/nvme0n1p5. also for hibernation?
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
